# Site settings
title: Postop (SRS) Care 101
email: unknowndevice@gmail.com
description: Tips and tricks to help on your recovery from MTF SRS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://postopcare.github.io" # the base hostname & protocol for your site
header-img: "img/home-bg.jpg"
#twitter_username: ""
github_username:  "postopcare"
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

